AppBundle\Entity\Merchant:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MerchantRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        code:
            type: string
            length: 6
            unique: true
        feedUrl:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
