AppBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        designation:
            type: string
            length: 255
            unique: true
        eanCode:
            type: string
            length: '13'
            unique: true
    lifecycleCallbacks: {  }
